Belajar_Django_4/letstalk/User/urls.py
from django.urls import path 
from . import views

app_name = 'USER'

urlpatterns = [
    path('', views.userpage, name='profile'),
    
]

Belajar_Django_4/letstalk/letstalk/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf.urls.static import static
from django.conf import settings



urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', views.Login, name='login'),
    path('logout/', views.LOGOUT, name='logout'),
    path('post/<int:ID>', views.post, name='post'),
    path('register/', views.signup, name='register'),
    path('', views.homepage, name='home'),
    path('user/', include('User.urls')),
    path('post/', include('post.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Belajar_Django_4/letstalk/post/urls.py
from django.urls import path
from . import views

app_name = 'post'

urlpatterns = [
    path('', views.Create_Post, name='createpost'),
    ]

Belajar_Django_4/letstalk/User/models.py
from django.db import models

# Create your models here.

Belajar_Django_4/letstalk/post/models.py
from django.db import models
from django.contrib.auth.models import User


class CreatePost(models.Model):
    content = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    banner = models.FileField()
    author = models.ForeignKey(User, on_delete=models.CASCADE, default=None)
    like = models.ManyToManyField(User, blank=True, related_name="like")
    def __str__(self):
        return self.content
    
    
class Comment(models.Model):
    post = models.ForeignKey(CreatePost, on_delete=models.CASCADE, related_name='comments')
    date = models.DateTimeField(auto_now_add=True)
    pengguna = models.ForeignKey(User, on_delete=models.CASCADE)
    comment_text = models.TextField()
    
    def __str__(self) :
        return self.comment_text
    
    
    

Belajar_Django_4/letstalk/post/forms.py
from django import forms
from . import models

class NewPost(forms.ModelForm):
    class Meta:
        model = models.CreatePost
        fields = ['content', 'banner']
        widgets = {
            'content': forms.Textarea(attrs={'class': 'form-content', 'placeholder': 'Your content'}),
            'banner': forms.FileInput(attrs={'class': 'form-banner'}),
        }
        
class CommentForm(forms.ModelForm):
    comment_text = forms.CharField(widget=forms.Textarea(attrs={'class': 'fields'}))
    class Meta:
        model = models.Comment
        fields = ('comment_text',)

Belajar_Django_4/letstalk/User/views.py
from django.shortcuts import render, redirect
from post.models import CreatePost
from post import forms


# Create your views here.
APP_NAME = 'user'


def userpage(request):
    post = CreatePost.objects.filter(author=request.user).order_by('-date')
    UpdateForm = CreatePost.objects.all()
    if request.method == 'POST':
        if 'delete' in request.POST:
            pk = request.POST.get('delete')
            postingan = CreatePost.objects.get(id=pk)
            postingan.delete()
        elif 'edit' in request.POST:
            pk = request.POST.get('edit')
            postingan = CreatePost.objects.get(id=pk)
            UpdateForm = forms.NewPost(instance=postingan)
        elif 'save' in request.POST:
            pk = request.POST.get('save')
            postingan = CreatePost.objects.get(id=pk)
            UpdateForm = forms.NewPost(request.POST, request.FILES or None, instance=postingan)
            if UpdateForm.is_valid():
                UpdateForm.save()
                return redirect ('USER:profile')
            UpdateForm = CreatePost()
        else:
            UpdateForm =forms. NewPost(request.FILES or None, instance=postingan)
    context = {
        'UpdateForm': UpdateForm,
        'post': post,
        'title' : 'Profile'
    }
    return render(request, 'user/userpage.html', context)
    

Belajar_Django_4/letstalk/letstalk/views.py
from django.shortcuts import render,redirect, get_object_or_404
from post.models import CreatePost, Comment
from django.http import JsonResponse, HttpResponseRedirect, HttpResponse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from post.forms import CommentForm
from django.urls import reverse
    
    
    
def homepage(request):
    allpost = CreatePost.objects.all().order_by('-date')
    context = {
        'allpost': allpost,
        'title':'Home',
    }
    return render(request,'home.html', context)
            

        
def Login(request):
    response_data = {}
    if request.method == "POST" and request.headers.get('x-requested-with') == 'XMLHttpRequest':
        username = request.POST ['username']
        password = request.POST ['password']
        
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                response_data = {'Login': 'success'}
    else:
        user = authenticate(username=username, password=password)
    
    return JsonResponse(response_data)


def LOGOUT (request):
    if request.method == 'POST':
        logout(request)
        return redirect('home')

def signup(request):
    response_data = {}
    if request.method == "POST":
        username = request.POST ['username']
        password = request.POST ['password']
    
        newuser = User.objects.create(username=username)
        newuser.set_password(password)
        newuser.save()
        response_data = {'registers': 'success'}
        return JsonResponse(response_data)
        
    return JsonResponse(response_data)


def post(request, ID):
    post = CreatePost.objects.filter( id=ID)
    postingan = get_object_or_404(CreatePost, id=ID)
    total_comments = Comment.objects.filter(id=ID).count()
    user = request.user
    
    comments = Comment.objects.filter(post=postingan).order_by("-date")
    
    
    
    if request.method == 'POST':
        is_liked = False    
        commentform = CommentForm(request.POST)
        if commentform.is_valid():
            comment = commentform.save(commit=False)
            comment.post = postingan
            comment.pengguna = user
            comment.save()

        if "like" in request.POST:
            postingan.like.add(request.user)
            is_liked = True
            
        elif "dislike" in request.POST:
            postingan.like.remove(request.user)
            is_liked = False
        
        elif "delete" in request.POST:
            pk = request.POST.get('delete')
            delete_c = Comment.objects.get(pk=pk)
            delete_c.delete()
            
        return HttpResponseRedirect(reverse('post', args=[ID]), {'is_liked': is_liked})
    
    else:
        
        commentform = CommentForm()
    
    context = {
        'total_comments': total_comments,
        'commentform': commentform,
        'commentlist' : comments,
        'postingan': post,
        'title': 'Post'
    }
    return render(request, 'post.html', context)

Belajar_Django_4/letstalk/post/views.py
from django.shortcuts import render, redirect
from . import forms
from .models import Comment
from django.http import JsonResponse


# Create your views here.
def Create_Post(request):
    if request.method == 'POST':
        CreatePost = forms.NewPost(request.POST, request.FILES)
        if CreatePost.is_valid():
            newpost = CreatePost.save(commit=False)
            newpost.author = request.user
            newpost.save()
            return redirect('home')
            
    else:
        CreatePost = forms.NewPost()
    return render(request, 'post/createpost.html', {'CreatePost': CreatePost})

Belajar_Django_4/letstalk/User/templates/user/userpage.html
{% extends "main.html" %}
{% load static %}
{% load widget_tweaks %}

{% block link_css %}
<link rel="stylesheet" href="{% static "user/css/style.css" %}">
{% endblock link_css %}


{% block content %}
<section class="content">
    <form action="{% url "USER:profile" %}" class="postingan" method="post" enctype="multipart/form-data">  
        {% csrf_token %}
        {% for user_post in post %}
            {% if UpdateForm.instance.id == user_post.id %}
            <section class="section">
                <div class="edit-form">
                    <span>Edit Post</span>
                    {% csrf_token %}
                    <label for="content" class="label">Content</label>
                    {% render_field UpdateForm.content id="content" %}
                    <label for="banner" class="label">Chose Image</label>
                    {% render_field UpdateForm.banner id="banner"%}
                    <button class="btn-post" name="save" value="{{ user_post.id }}">Save</button>
                </div>
            </section>
            {% else %}
            <section class="post" value="{{ user_post.id }}">
                <h3>{{ user_post.author}}</h3>
                <div class="gambar">
                    {% if user_post.banner.name|slice:"-3:" == 'mp4'  %}
                    <video controls="controls">
                        <source src="{{ user_post.banner.url }}" type='video/mp4' >
                    </video>
                    {% endif %}
                    {% if user_post.banner.name|slice:"-4:" == 'jpg' or 'png' or 'jfif' %}
                        <img src="{{user_post.banner.url }}" alt="" >
                    {% endif %}
                </div>
                <p>{{ user_post.date }}</p>
                <div class="menu">
                    <a href="{% url "post" user_post.id %}" >
                        <i class='bx bx-comment'></i>
                    </a>
                    <button name="edit" class="btn btn-edit" value="{{ user_post.id }}" formnovalidate >
                        <i class='bx bx-message-edit'></i>
                    </button>
                    <button name="delete" class="btn btn-delete" value="{{ user_post.id }}" formnovalidate >
                        <i class='bx bx-trash'></i>
                    </button>
                </div>
                
                <p>{{ user_post.content }}</p>
                    
            </section>
            {% endif %}
        {% endfor %}
    </form>
</section>
{% endblock content %}

Belajar_Django_4/letstalk/post/templates/post/createpost.html
{% extends "main.html" %}
{% load static %}
{% load widget_tweaks %}

{% block link_css %}
<link rel="stylesheet" href="{% static "/post/css/createpoststyle.css" %}">
{% endblock link_css %}


{% block content %}
<section class="section">
    <form class="createpost" action="{% url "post:createpost" %}" method="post" enctype="multipart/form-data">
        <span>Create Post</span>
        {% csrf_token %}
        <label for="content" class="label">Content</label>
        {% render_field CreatePost.content id="content" %}
        <label for="banner" class="label">Chose Image</label>
        {% render_field CreatePost.banner id="banner" %}
        <button class="btn-post">Post</button>
    </form>
</section>
{% endblock content %}

Belajar_Django_4/letstalk/templates/home.html
{% extends "main.html" %}
{% load static %}
{% load widget_tweaks %}

{% block link_css %}
<link rel="stylesheet" href="{% static "css/style.css" %}">
{% endblock link_css %}

{% block content %}
<section class="content">
    <section class="post">
        
        <!-- post display -->
            {% for post in allpost %}
            
                <h3>{{ post.author }}</h3>
                <div class="gambar">
                    {% if post.banner.name|slice:"-3:" == 'mp4'  %}
                    <video controls="controls">
                        <source src="{{ post.banner.url }}" type='video/mp4' >
                    </video>
                    {% endif %}
                    {% if post.banner.name|slice:"-4:" == 'jpg' or 'png' or 'jfif' %}
                        <img src="{{post.banner.url }}" alt="" >
                    {% endif %}
                </div>
                <p>{{ post.date }}</p>
                <a href="{% url "post" post.id %}" class="detail">
                    <i class='bx bxs-chevrons-right'></i> <span>post details</span>
                </a>
                
                    <p>{{ post.content }}</p>
                    
                    <!-- post display -->
                <hr>
            {% endfor %}
        </form>
    </section>
</section>
{% endblock content %}

Belajar_Django_4/letstalk/templates/like.html
<form action="{% url "like" %}" method="post" >
    {% csrf_token %}
    {% if is_like  %}
    <button type="submit" name="ID" class="like" value="{{ post.id }}" id="ID">
        <i class='bx bxs-heart'></i> <!-- like -->
        like
    </button>
    {% else %}
    <button type="submit" name="ID" class="unlike" value="{{ post.id }}" id="ID">
        <i class='bx bx-heart'></i> <!-- unlike -->
        unlike
    </button>
    {% endif %}
    <p>like: {{ post.like.count }}</p>
</form>

Belajar_Django_4/letstalk/templates/main.html
<!DOCTYPE html>
{% load widget_tweaks %}
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- favicon -->
    <link rel="icon" type="image/png" sizes="32x32" href="{% static "img/favicon-32x32.png" %}">
    <!-- favicon -->
    <!-- awal icon -->
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
    <!-- akhir icon -->
    <!-- awal font -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&family=Oxanium:wght@200..800&display=swap" rel="stylesheet">
    <!-- akhir font -->
    
    <!-- ajax -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <!-- ajax -->


    {% block link_css %}

    {% endblock link_css %}
    <link rel="stylesheet" href="{% static '/css/mainstyle.css' %}">


    <title>{{ title }}</title>
</head>
<body>
    <!-- awal container -->
    <div class="container">
        <!-- awal sidebar -->
        <div class="sidebar">
            <h1>Lets Talk</h1>
            <h2>L T</h2>
            <ul>
                <li>
                    <a href="{% url "home" %}">
                        <i class="bx bx-home-heart"></i>
                        <span class="tooltip1">Home</span>
                    </a>
                </li>
                {% if user.is_authenticated %}
                <li>
                    <a href="{% url "USER:profile" %}">
                        <i class="bx bxs-user-detail"></i>
                        <span class="tooltip1">Profile</span>
                    </a>
                </li>
                <li>
                    <a href="{% url "post:createpost" %}">
                        <i class="bx bx-list-plus"></i>
                        <span class="tooltip1">Create Post</span>
                    </a>
                </li>
                <form action="{% url "logout" %}" method="post">
                    {% csrf_token %}
                    <button>
                        <i class="bx bx-log-out-circle"></i>
                        <span class="tooltip1">Logout</span>
                        
                    </button>
                </form>
                {% else %}
                <button class='btn-signup'>
                    <i class="bx bx-user-plus"></i>
                    <span class="tooltip1">Sign Up</span>
                </button>

                <button class='btn-login'>
                    <i class="bx bx-log-in-circle"></i>
                    <span class="tooltip1">Login</span>
                </button>
                {% endif %}
                    
            </ul>
        </div>
        <!-- akhir sidebar -->


        <!-- awal mainpost -->
        <div class="mainpost">
            <h1>Lets Talk</h1>
            {% block content %}
            {% endblock content %}
            <!-- awal login -->
            <div class="login overlay">
                <div class="form">
                    <button class="btn-close">
                        <i class='bx bx-x-circle'></i>
                    </button>
                    <form class="loginform"  >
                        <span>Login</span>
                        {% csrf_token %}
                        <label for="username">Username</label>
                        <input type="text" id="username" class="fields" placeholder="Your Username" name="username"> 
                        <label for="password">Password</label>
                        <input type="password" id="password" class="fields" placeholder="Your Password" name="password">
                        <button class="kirim" type="submit">Login</button>
                    </form>
                    
                </div>
            </div>
            <!-- akhir login -->
            
            <!-- awal register -->
            <div class="register overlay">
                <div class="form">
                    <button class="btn-close">
                        <i class='bx bx-x-circle'></i>
                    </button>
                    <form class="registerform"  >
                        <span>Register</span>
                        {% csrf_token %}
                        <label for="username">Username</label>
                        <input type="text" id="username1" class="fields" placeholder="Your Username" name="username1"> 
                        <label for="password1">Password</label>
                        <input type="password" id="password1" class="fields" placeholder="Your Username" name="password1"> 
                        <button class="kirim" type="submit">Sign Up</button>
                    </form>
                    
                </div>
            </div>
            <!-- register register -->


        </div> 
        <!-- akhir mainpost -->
        
        <div class="warning">
            <p class="p1">This</p>
            <p class="p2">is</p>
            <p class="p3">a</p>
            <p class="p4">dummy</p>
            <p class="p5">website</p>
            <p class="p6">All</p>
            <p class="p7">data</p>
            <p class="p8">will</p>
            <p class="p9">not</p>
            <p class="p10">be</p>
            <p class="p11">safe</p>
            <p class="p12">Don't</p>
            <p class="p13">share</p>
            <p class="p14">any</p>
            <p class="p15">private</p>
            <p class="p16">info.</p>
        </div>

    </div>
    <!-- akhir container -->


     <!-- awal navbar -->
    <nav>
        <div class="navbar">
            <ul>
                <li>
                <!-- home -->
                    <a href="{% url "home" %}">
                        <i class="bx bx-home-heart"></i>
                    </a>
                </li>
                {% if user.is_authenticated %}
                <!-- profile -->
                <li>
                    <a href="{% url "USER:profile" %}">
                        <i class="bx bxs-user-detail"></i>
                    </a>
                </li>
                <!-- create post -->
                <li>
                    <a href="{% url "post:createpost" %}">
                        <i class="bx bx-list-plus"></i>
                    </a>
                </li>
                <form action="{% url "logout" %}" method="post">
                    {% csrf_token %}
                    <button>
                        <i class="bx bx-log-out-circle"></i>
                    </button>
                </form>
                {% else %}
                
                <!-- create acc -->
                <button class='btn-signup'>
                    <i class="bx bx-user-plus"></i>
                </button>

                <button class='btn-login'>
                    <i class="bx bx-log-in-circle"></i>
                </button>
                {% endif %}
                
            </ul>
        </div>
    </nav>
    <!-- akhir navbar -->
    
    <!-- script -->

    {% block scripts %}
    
    {% endblock scripts %}
    <!-- script -->
    
    <!-- login -->
    <script type="text/javascript">
        let loginov = document.querySelector('.login');
        let registerov = document.querySelector('.register');

        $(document).on('submit', '.loginform', function(e) {
            e.preventDefault();
            $.ajax({
                type: 'POST',
                url : "{% url "login" %}",
                data : {
                    username : $('#username').val(),
                    password : $('#password').val(),
                    csrfmiddlewaretoken : $('input[name=csrfmiddlewaretoken]').val(),
                },
            success: function(data) {
                $('.overlay').hide();
                $(document).ajaxStop(function(){
                    window.location.reload();
                });
            }
        })
            
        });


        $(document).on('submit', '.registerform', function(e) {
            e.preventDefault();
            $.ajax({
                type: 'POST',
                url : "{% url "register" %}",
                data : {
                    username : $('#username1').val(),
                    password : $('#password1').val(),
                    csrfmiddlewaretoken : $('input[name=csrfmiddlewaretoken]').val(),
                },
            success: function(data) {
                $(document).ajaxStop(function(){
                    registerov.classList.remove('active');
                    loginov.classList.add('active');
                });
            }
        })
            
        });


    </script>
    <!-- login -->
    


    <!-- overlay -->
    <script>
        let loginoverlay = document.querySelector('.login');
        let registeroverlay = document.querySelector('.register');
        
        $(function(){
            $('.btn-signup').click(function(){
                registeroverlay.classList.add('active');
                loginoverlay.classList.remove('active');
                return false
            });
            $('.btn-login').click(function(){
                registeroverlay.classList.remove('active');
                loginoverlay.classList.add('active');
                return false
            });
            $('.btn-close').click(function(){
                registeroverlay.classList.remove('active');
                loginoverlay.classList.remove('active');
            });
        });
    </script>
    <!-- overlay -->

</body>
</html>

Belajar_Django_4/letstalk/templates/post.html
{% extends "main.html" %}
{% load static %}
{% load widget_tweaks %}

{% block link_css %}
<link rel="stylesheet" href="{% static "css/poststyle.css" %}">
{% endblock link_css %}

{% block content %}
<section class="content">
    <section class="post">
        
        <!-- post display -->
        {% for post in postingan %}
            <h3>{{ post.author }}</h3>
            <div class="gambar">
                {% if post.banner.name|slice:"-3:" == 'mp4'  %}
                <video controls="controls">
                    <source src="{{ post.banner.url }}" type='video/mp4' >
                </video>
                {% endif %}
                {% if post.banner.name|slice:"-4:" == 'jpg' or 'png' or 'jfif' %}
                    <img src="{{post.banner.url }}" alt="" >
                {% endif %}
            </div>
            <p>{{ post.date }}</p>
                {% if user.is_authenticated %}
                <form action="" method="post" >
                    {% csrf_token %}
                    <button type="submit" name="dislike" class="unlike" value="{{ post.id }}" >
                        <i class='bx bx-heart'></i> <!-- unlike -->
                        Dislike
                    </button>
                    <button type="submit" name="like" class="like" value="{{ post.id }}" >
                        <i class='bx bxs-heart'></i> <!-- like -->
                        Like
                    </button>
                </form>
                {% endif %}
                <p>like: {{ post.like.count }}</p> 
                <p>Comments: {{ post.comments.count }}</p>
                
                <p>{{ post.content }}</p>
                
                <!-- post display -->
            <hr>
            {% endfor %}
            <div class="comment-section">
                <p>Comment list</p>
                <form action="" method="post">
                    {% csrf_token %}
                {% for comment in commentlist %}
                    <p>{{ comment.pengguna }}</p>
                    <p>{{ comment.comment_text}}</p>
                    {% if request.user == comment.pengguna %}
                    <button class="btn-dlt" name="delete" value="{{ comment.id }}">
                        Delete
                    </button>
                    {% endif %}
                    <hr>
                {% endfor %}
                </form>
            </div>
            {% if user.is_authenticated %}
            <form action="" class="comment" method="post">
                {% for commentForm in commentform %}
                {% csrf_token %}
                <label >comment</label>
                {{ commentForm }}
                <button type="submit" class="btn">
                    <i class='bx bxs-send'></i>
                </button>
                {% endfor %}
            </form>
            {% endif %}
        
    </section>
</section>

{% endblock content %}