Belajar_Django_1/letstalk/User/urls.py
from django.urls import path 
from . import views

app_name = 'USER'

urlpatterns = [
    path('', views.userpage,),
    path('register/', views.register, name='register'),
    path('logout/', views.LOGOUT, name='logout')
]

Belajar_Django_1/letstalk/letstalk/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.homepage, name='home'),
    path('login/', views.userlogin, name='login'),
    path('user/', include('User.urls')),
    path('post/', include('post.urls')),
    # path('user/', include('User.urls')),
    # path('post/', include('post.urls')),
]

Belajar_Django_1/letstalk/post/urls.py
from django.urls import path
from . import views

app_name = 'post'

urlpatterns = [
    path('', views.postlist, name='postlist')
    
    ]

Belajar_Django_1/letstalk/post/models.py
from django.db import models

Belajar_Django_1/letstalk/User/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import logout
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages




# Create your views here.
APP_NAME = 'user'


def userpage(request):
    context = {
        'title' : 'Profile'
    }
    return render(request, f'{APP_NAME}/userpage.html', context)
    
def register(request):
    if request.method == 'POST':
        createUser = UserCreationForm(request.POST)
        if createUser.is_valid():
            createUser.save()
            return redirect('login')
        
    else:
        
        createUser = UserCreationForm()
        
        
    context = {
        'title': 'Registration',
        'createUser': createUser,
    }
    return render(request, 'user/register.html', context)
    
def LOGOUT (request):
    if request.method == 'POST':
        logout(request)
        return redirect('home')

Belajar_Django_1/letstalk/letstalk/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, authenticate
    

def userlogin(request):
    if request.method == "POST":
        userlogin = AuthenticationForm(data=request.POST)
        if userlogin.is_valid():
            login(request, userlogin.get_user())
            return redirect('home')
    else:
        userlogin = AuthenticationForm()
    
    context = {
        'title':'login',
        'userlogin': userlogin,
    }
    
    return render(request, 'loginuser.html', context)


def homepage(request):
    context = {
        'title':'Home',
    }
    return render(request, 'home.html' , context)
            
    

Belajar_Django_1/letstalk/post/views.py
from django.shortcuts import render

# Create your views here.
def postlist(request):
    return render(request, 'post/post.html')

Belajar_Django_1/letstalk/templates/home.html
{% extends "main.html" %}

Belajar_Django_1/letstalk/templates/loginuser.html
{% extends "main.html" %}
{% load widget_tweaks %}
{% load static %}


{% block link_css %}
<link rel="stylesheet" href="{% static "/css/style.css" %}">
{% endblock link_css %}


{% block FORM %}
<div class="formoverlay">
    <div class="form">
    <button class="close">
        <i class='bx bxs-x-circle'></i>
    </button>
        <form class="LOGINFORM" action="" method="post">
            {% csrf_token %}
            {% if userlogin.errors %}
            <p class="error">!! Please Enter a Correct Username And Password</p>
            {% endif %}
            <label for="username">Username</label>
            {% render_field userlogin.username id="USERNAME" class="USERNAME" placeholder="Input Username" %}
            <label for="PASSWORD">Password</label>
            {% render_field userlogin.password id="PASsWORD" class="PASSWORD"  placeholder="Input Password"%}
            <button>Login</button>
        </form>
    </div>
</div>
{% endblock FORM %}
{% block script %}
<script>    
    const closeButton = document.querySelector('.close');
    const close = document.querySelector('.formoverlay');
    
    closeButton.addEventListener('click', function(){
        close.classList.add('active');
    });
</script>
{% endblock script %}

Belajar_Django_1/letstalk/templates/main.html
<!DOCTYPE html>
{% load widget_tweaks %}
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- awal icon -->
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
    <!-- akhir icon -->
    <!-- awal font -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&family=Oxanium:wght@200..800&display=swap" rel="stylesheet">
    <!-- akhir font -->

    {% block link_css %}

    {% endblock link_css %}
    <link rel="stylesheet" href="{% static '/css/mainstyle.css' %}">


    <title>{{ title }}</title>
</head>
<body>
    <!-- awal overlay login -->
    {% block FORM %}
    <div class="formoverlay">
        <div class="form">
            
        </div>
    </div>
    {% endblock FORM %}
    <!-- akhir overlay login -->


    


    <!-- awal container -->
    <div class="container">
        <!-- awal sidebar -->
        <div class="sidebar">
            <h1>Lets Talk</h1>
            <h2>L T</h2>
            <ul>
                <li>
                    <a href="{% url "home" %}">
                        <i class="bx bx-home-heart"></i>
                        <span class="tooltip1">Home</span>
                    </a>
                </li>
                {% if user.is_authenticated %}
                <li>
                    <a href="{% url "post:postlist" %}">
                        <i class="bx bxs-user-detail"></i>
                        <span class="tooltip1">Profile</span>
                    </a>
                </li>
                <li>
                    <a href="#">
                        <i class="bx bx-list-plus"></i>
                        <span class="tooltip1">Create Post</span>
                    </a>
                </li>
                <form action="{% url "USER:logout" %}" method="post">
                    {% csrf_token %}
                    <button>
                        <i class="bx bx-log-out-circle"></i>
                        <span class="tooltip1">Logout</span>
                        
                    </button>
                </form>
                {% else %}
                <li>
                    <a href="{% url "USER:register" %}">
                        <i class="bx bx-user-plus"></i>
                        <span class="tooltip1">Sign Up</span>
                    </a>
                </li>
                
                <li>
                    <a href="{% url "login" %}">
                        <i class="bx bx-log-in-circle"></i>
                        <span class="tooltip1">login</span>
                    </a>
                </li>
                
                <!-- <button>
                    <span class="tooltip1">Login</span>
                </button>
                -->
                {% endif %}
                    
            </ul>
        </div>
        <!-- akhir sidebar -->


        <!-- awal sidebar -->
        <div class="mainpost">
            <section>
                <h1>Lets Talk</h1>
                <h3>User</h3>
                <div class="gambar">
                    <img src="{% static 'img/gambar1.jpg' %}" alt="">
                </div>
                <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nulla iure velit labore dignissimos cum nesciunt animi, deserunt recusandae! Quas ab nobis atque, mollitia quos autem nulla ipsum repellendus sit nihil totam ipsa inventore recusandae voluptate odio corrupti dolores quisquam saepe dolorum nemo iure esse, cumque fugiat tenetur? Eum at corporis modi ab vitae incidunt blanditiis harum sequi repudiandae deserunt ipsam esse eveniet laborum ex, dolorem adipisci officiis quaerat quibusdam architecto asperiores molestias necessitatibus? Praesentium sunt nam asperiores modi! Praesentium quidem sunt sint facere, est corrupti molestias quam hic vitae! Asperiores illum amet nobis perferendis exercitationem ut nisi eum animi necessitatibus.</p>
                <ul>
                    <li><a href="#">Komentar</a></li>
                </ul>
                <hr>
            </section>
        </div> 
        <!-- akhir sidebar -->


    </div>
    <!-- akhir container -->


     <!-- awal navbar -->
    <nav>
        <div class="navbar">
            <ul>
                <li>
                <!-- home -->
                    <a href="/">
                        <i class="bx bx-home-heart"></i>
                    </a>
                </li>
                {% if user.is_authenticated %}
                <!-- profile -->
                <li>
                    <a href="#">
                        <i class="bx bxs-user-detail"></i>
                    </a>
                </li>
                <!-- create post -->
                <li>
                    <a href="#">
                        <i class="bx bx-list-plus"></i>
                    </a>
                </li>
                <form action="{% url "USER:logout" %}" method="post">
                    {% csrf_token %}
                    <button>
                        <i class="bx bx-log-out-circle"></i>
                    </button>
                </form>
                {% else %}
                
                <!-- create acc -->
                <li>
                    <a href="{% url "USER:register" %}">
                        <i class="bx bx-user-plus"></i>
                    </a>
                </li>
                <li>
                    <a href="{% url "login" %}">
                        <i class="bx bx-log-in-circle"></i>
                    </a>
                </li>
                {% endif %}
                
            </ul>
        </div>
    </nav>
    <!-- akhir navbar -->
    {% block script %}
    
    {% endblock script %}
    
    
</body>
</html>